### ISSUE TITLE
Input type=email multiple changes first character

### ISSUE THREAD

**Issue by goatandsheep** [mfranzke/datalist-polyfill#1]
### Description

When entering multiple entries on Input type email, the first character of the first e-mail is changed. The activity is different each time you try to reproduce it.

### Expected outcome

* The selected e-mail appears
* The previous inputs stay the same

### Actual outcome

* The selected e-mail appears
* **First character of first e-mail changes**

### Live Demo

[The default jsfiddle demo provided](https://jsfiddle.net/mfranzke/s6awjfze/)

### Steps to reproduce

1. Select an e-mail
2. Type comma
3. Select a second e-mail

**Comment by mfranzke** [comment]
@goatandsheep, thanks a lot for providing your feedback !

I sadly cannot reproduce any misbehaviour and neither could explain that out of the JavaScript code. I've tested on my local machine (Mac OS X El Capitan 10.11.6, with Safari 10.1.2), and used the following process:

Open https://jsfiddle.net/mfranzke/s6awjfze/
Focus the email field within the fieldset regarding "input type email" and type in the letter "m"
Select the email-address info@davidhasselhoffonline.com
Focus the email field within the fieldset regarding "input type email“, get to the end of the value and type in a comma and than the letter "j"
Select the email-address john@doe
The resulting value within the "input type email" field is "info@davidhasselhoffonline.com,john@doe"

Could you please provide more information regarding both your system and your exact values that you've chosen for me to reproduce your experienced behaviour as well?

**Comment by goatandsheep** [comment]
Sorry about that. I think it's actually a Chrome bug. I tested the multi email datalist outside your environment and it still came up. When sending this ticket I forgot that this polyfill leaves Chrome as is.
