### ISSUE TITLE
React compatibility

### ISSUE THREAD

**Issue by cmwint** [mfranzke/datalist-polyfill#17]
Will this polyfill work with react? If so, how can it be implemented in a component? I'd love some help, please!

Thank you for a great polyfill!

**Comment by mfranzke** [comment]
Hi @cmwint,

thanks a lot for your request.

The polyfill should work with any dynamic HTML like e.g. being generated by react quite nicely, based on its core concepts of e.g. event delegaton.

As I'm not necessarily a react expert, I've just forked and hacked the react boilerplate/example by JSFiddle a little bit et voila , looks fine to me:
https://jsfiddle.net/mfranzke/0f4nrzsg/

In general you wouldn't need to include this polyfill in a component as it aims to provide support for the datalist element in general. That for just integrating it globally should even already do the trick (as I did within JSFiddle).


Cheers,
Maximilian

**Comment by cmwint** [comment]
Thank you for this example! I appreciate your response!

**Comment by mfranzke** [comment]
Sure, you're welcome. If there's something else I could help you with, please feel free to contact me again.

**Comment by mfranzke** [comment]
@pdkeating-globo, as I‘m no react expert, I sadly couldn‘t help with this question for sure.

But I would think that these are two seperate things: by npm you‘re managing your dependencies in a way that they are being resolved (installed) to your environment to work with those afterwards.

And by including or referencing them via some kind mechanism (<script> tag, webpack, etc.pp.) you would be able to use them within your code.

So you at least have them available in your environment after installing them via npm, but now you need to include/reference them the react way (whatever that exactly is).
