### ISSUE TITLE
allow re-initialization

### ISSUE THREAD

**Issue by mertenhanisch** [mfranzke/datalist-polyfill#3]
especially for this kind of feature, you sometimes want to create the datalist element with javascript, after the initial page rendering. it would be very useful, if one could rerun the polyfill after datalist creation, to apply the polyfill to the new element. in the current form the polyfill script runs once, when included and does not run again when new datalist elements are being created.

**Comment by mfranzke** [comment]
@mertenhanisch, thanks a lot for your feedback.

As I'm not aware of that the polyfill wouldn't work for elements created and injected or either just manipulated (like the datalists options) after the initial page load, could you please provide a testcase or the code that you've tested this with?

**Comment by mfranzke** [comment]
Even though that the following code might be a very simple example, it does the job on creating form elements and inject them into the DOM after the script has been executed - and it works pretty fine. So I can't identify an issue here.

```javascript
// create the elements ...
$fieldset = document.createElement( 'fieldset' );

$input = document.createElement( 'input' );
$input.setAttribute( 'type', 'text' );
$input.setAttribute( 'name', 'testinput1' );
$input.setAttribute( 'id', 'testinput1' );
$input.setAttribute( 'list', 'testoptions1' );

$datalist = document.createElement( 'datalist' );
$datalist.setAttribute( 'id', 'testoptions1' );
$datalist.setAttribute( 'title', 'Choose a suggestion' );

$option1 = document.createElement( 'option' );
$option1.setAttribute( 'value', 'Test Option 1' );

$option2 = document.createElement( 'option' );
$option2.setAttribute( 'value', 'Test Option 2' );

$option3 = document.createElement( 'option' );
$option3.setAttribute( 'value', 'Test Option 3' );

// ... and stick them into each other ...
$datalist.appendChild( $option1 );
$datalist.appendChild( $option2 );
$datalist.appendChild( $option3 );

$fieldset.appendChild( $input );
$fieldset.appendChild( $datalist );

// ... and append those to the body
document.body.appendChild( $fieldset );
```

**Comment by mertenhanisch** [comment]
Thank you for taking the time. I played around more with your fiddle in safari, and it turns out it seems to be just a styling problem (datalist and select element not where I was looking for them). So, sorry, and yes your polyfill already is dynamic-proof, as you describe in the readme :)

**Comment by mfranzke** [comment]
easy peasy.
