### ISSUE TITLE
Enable on Edge and IE11

### ISSUE THREAD

**Issue by eddr** [mfranzke/datalist-polyfill#36]
Hi

Edge datalist implementation is buggy (practically not working) - can the polyfill be enabled for Edge too?
Tried to remove the check at the beginning of the screen, but it doesn't seem to solve the problem.

Thanks

**Comment by eddr** [comment]
Thanks!

Yes, looking up a text from the middle of the option's text gives no results.
Example: Looking up "o" won't give you that "Dog" option

This is also the behavior I see in the basic demo you've published (both Edge and IE11)

I understand that's it harder. Maybe it could be activated for a custom element? not sure it's a good idea, but still.

**Comment by mfranzke** [comment]
Valid point, thanks a lot for that finding !!

**Comment by mfranzke** [comment]
@eddr, are there any further findings by you on incompatible/missing support of features or behaviours?

**Comment by eddr** [comment]
I guess that's what already been described - that the 'change' doesn't register, I think. Nothing occures

Anything to do with these behaviors?

**Comment by mfranzke** [comment]
At least regarding the substring matching something came to my mind - let me think this through and I‘ll most likely be able to provide a solution soon.

**Comment by muelli** [comment]
> So is there anything else that you've identified regarding a buggy behavior on this browsers?

In IE11 the list pops up immediately after the input element has focus. That is annoying especially when the datalist has many items. Other browsers seem require a character to be typed in or a double click.

**Comment by mfranzke** [comment]
@muelli, valid finding !

But on the other hand, both the spec doesn't seem to define anything on the expected behavior and Google Chrome seems to do that as well.

In general I'd like to only enable non-existing /-working functionality within those browsers in the context of this polyfill, and not influence with their partly different UI/UX.

**Comment by mfranzke** [comment]
I've opened a new ticket for handling the missing substring matching: #39

**Comment by mfranzke** [comment]
@muelli, okay, thank you for pointing that out.

**Comment by mfranzke** [comment]
The main purpose of this polyfill have been enhanced by #39
