### ISSUE TITLE
No substring matching for the suggestions in IE11+ and EDGE

### ISSUE THREAD

**Issue by mfranzke** [mfranzke/datalist-polyfill#39]
It's even also already aligned with Microsoft that both IE11+ and EDGE are missing to "search both the value and label, using substring matching; currently it searches both the value and label, but uses prefix matching"
source: https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/9573654/

**Comment by eddr** [comment]
nice! looking forward to it!
