### ISSUE TITLE
Enhancement : access to selected option

### ISSUE THREAD

**Issue by eddr** [mfranzke/datalist-polyfill#41]
Thanks for all the effort.

In datalist it's currently not possible to differentiate option's value from text (probably because you can enter free text)
However, it is very useful for some. So, I thought perhaps accessing the selected option - if there is one - is a simpler solution that will allow accessing to the element data (like data-id='x'). 

What do you think?

**Comment by mfranzke** [comment]
Sure, you're welcome !

And I'm not totally sure, what you exactly mean by your request. I think it's mainly about the latter part and that you like to get to know the currently selected element within the `select` that emulates the functionality in IE9 and Safari, right?

You could e.g. request that index by the following function:
`document.querySelector('#optionslist select').options.selectedIndex`

**Comment by eddr** [comment]
1. Yes, that's true. Didn't about index necessarily, but yea - something to allow accessing that data
2. But there is no such a thing in Chrome/FF either, no?

**Comment by mfranzke** [comment]
Regarding 2:
Not to my knowledge. It seems like that there's no event regarding selecting values within the datalist suggestions native list, as I've seem to have figured out in a little experiment previously. But you might want to check the different events again, and check for event.target, event.relatedTarget etc.

**Comment by mfranzke** [comment]
@eddr, even also regarding my last comment, this could get closed now, couldn‘t it ?

**Comment by eddr** [comment]
Thanks. Wasn't around to reply.

**Comment by mfranzke** [comment]
Okay, easy.
