### ISSUE TITLE
Doesn't work at all on mobile safari

### ISSUE THREAD

**Issue by malinoff** [mfranzke/datalist-polyfill#43]
Hi, thank you for the project.

Unfortunately it doesn't render the input properly on mobile safari, here's the screenshot.
<img width="317" alt="screen shot 2018-10-08 at 20 52 03" src="https://user-images.githubusercontent.com/1702083/46616373-3c016200-cb3c-11e8-9f44-f663a75080dd.png">

Screenshot made from browserstack (`os=iOS&os_version=9.0&device=iPhone+6S&device_browser=safari`).

**Comment by mfranzke** [comment]
@malinoff, thanks a lot for your feedback.

What exactly do you mean by that it wouldn't work at all? In your description you're mainly mentioning the styling that looks a little off because of the select being displayed half-transparent and that for showing the border by the fieldset underneath.

**Comment by malinoff** [comment]
I mean behaviour is not the same like, say, on firefox.
<img width="238" alt="screen shot 2018-10-09 at 09 12 43" src="https://user-images.githubusercontent.com/1702083/46644768-941f7f00-cba3-11e8-8d0c-5075126d5cff.png">
Or on desktop safari
<img width="248" alt="screen shot 2018-10-09 at 09 13 57" src="https://user-images.githubusercontent.com/1702083/46644801-aef1f380-cba3-11e8-87b1-d476e88cf8f1.png">

**Comment by w-barath** [comment]
On iPhone 8Plus iOS12 it literally doesn't work at all.  It shows bare HTML inputs, that's all.  Looking over the source I can't see anything Safari or iOS-specific at all.  I see feature detection, but Safari advertises datalist DOMs but does not support datalist completion at all, so absolutely to support any version of Safari it must detect Safari and treat it like IE9.

**Comment by mfranzke** [comment]
w-barath, thanks a lot for your feedback. Which URL have you tested and could you please provide a screenshot?

**Comment by acespace90** [comment]
Yes, I can also confirm that on iOS it doesn't work properly.

![polyfill](https://user-images.githubusercontent.com/12846842/47211289-67364d80-d395-11e8-84d8-4138c0eaa757.gif)

**Comment by mfranzke** [comment]
@acespace90, thanks for feedback as well. As it works fine for me on the demo page on iOS (https://mfranzke.github.io/datalist-polyfill/demos/), could you please check that out and tell me whether it works for you over there?

**Comment by acespace90** [comment]
@mfranzke Yes it works, I checked before writing here :-) 
But I'm not understanding what is wrong with my code.

This is the code

```
<label for="text-field">
  From <span aria-hidden="true">*</span>
  <input id="text-field" type="text" class="" placeholder="Departure airport" value="" list="airports" required aria-required="true">
  <datalist id="airports" title="Choose an aiport">
      <option value="Bologna, Guglielmo Marconi [BLQ] (ITALIA)">
      <option value="Dubai, Al Maktoum Intl [DWC] (EMIRATI ARABI)">
      <option value="Roma, Fiumicino [FCO] (ITALIA)">
      <option value="New York Ny, John F Kennedy Intl [JFK] (STATI UNITI)">
      <option value="Parigi, Charles De Gaulle [CDG] (FRANCIA)">
      <option value="Berlino, Schoenefeld [SXF] (GERMANIA)">
      <option value="Londra, Heathrow [LHR] (REGNO UNITO)">
  </datalist>
</label>
```

**Comment by acespace90** [comment]
I noticed that the select appears behind the keyboard, but if I put the `datalist` out of `label` it works.
Any suggestions?

**Comment by AshotN** [comment]
Your demo didn’t work for me on Firefox, iOS version 11.14

**Comment by mfranzke** [comment]
@malinoff, thanks again for your feedback.

As we've aligned the polyfill actually does **work** on mobile, but doesn't look as probably expected (and shown on desktop browsers).
To my understanding a [polyfill](https://remysharp.com/2010/10/08/what-is-a-polyfill) should enable functionality on a non-supporting environment based on the standard APIs, which doesn't necessarily mean that it would look exactly the same as on other devices. I've chosen the standard _select_ element that displays as a list on Desktop browsers for its easy to use standard behavior regarding event handling etc. - but on mobile it obviously gets displayed as a closed _select_ with the regular spinner on focusing at the bottom of the screen for usability reasons.
Using a list and implementing all of the necessary surroundings as well as providing a non-optimal usability wasn't an option for me so that I want to keep it the way it's currently implemented.

**Comment by mfranzke** [comment]
@AshotN, do you have any more information for me on the aspects of your test and regarding which aspect it doesn't work? I've only had a Firefox on iOS version 12 available for a quick test and it works as expected.

**Comment by malinoff** [comment]
Unfortunately for a front-end polyfill, I think it's crucial to not only behave properly but also look properly. Otherwise, there's simply no point of using it in the first place while other javascript-based solutions exist, work and look the same everywhere.
I'd LOVE to use your polyfill/standard elements instead of custom js solutions. I honestly think that this is the right way to do frontend development, and while I don't have enough frontend skills to help you with code, I'm trying to help you with an honest user's feedback.
Of course, it's up to you to do something with it or to ignore it. I'd vote for option a though :)

**Comment by AshotN** [comment]
I have Firefox version 13.2. Latest on my OS. 


I didn’t do much besides open the demo and try tapping on the available option. Looked exactly like the first screenshot by OP

**Comment by mfranzke** [comment]
@malinoff, thanks for your previous feedback.

While I agree with what you're saying, there's no real discussion on whether the solution with the `select` "looks" properly in general - it's mainly about how Safari displays the values on its browser, which is in a collapsed select in this case. As this is their chosen solution for displaying larger lists, it's even also not "incorrect" for the polyfill, whereas other solutions probably have chosen to display an ordered list, that doesn't work that nicely on touch/mobile devices.

Plus that there's no other polyfill or solution out there, that does support as many of the features and is as standard compliant as this one (like e.g. even also supporting the lack of extended functionality on IE11+/EDGE).
