### ISSUE TITLE
Doesn't work on iOS when nesting the elements within the label element

### ISSUE THREAD

**Issue by mfranzke** [mfranzke/datalist-polyfill#44]
It doesn't work properly on iOS when **nesting** the elements within the _label_ element.

This is the code

```
<label for="text-field">
  From <span aria-hidden="true">*</span>
  <input id="text-field" type="text" class="" placeholder="Departure airport" value="" list="airports" required aria-required="true">
  <datalist id="airports" title="Choose an aiport">
      <option value="Bologna, Guglielmo Marconi [BLQ] (ITALIA)">
      <option value="Dubai, Al Maktoum Intl [DWC] (EMIRATI ARABI)">
      <option value="Roma, Fiumicino [FCO] (ITALIA)">
      <option value="New York Ny, John F Kennedy Intl [JFK] (STATI UNITI)">
      <option value="Parigi, Charles De Gaulle [CDG] (FRANCIA)">
      <option value="Berlino, Schoenefeld [SXF] (GERMANIA)">
      <option value="Londra, Heathrow [LHR] (REGNO UNITO)">
  </datalist>
</label>
```

I noticed that the select appears behind the keyboard, but if I put the `datalist` out of `label` it works.
Ok I tried to modify the markup also on the demo page and I confirm you that if `datalist` is inside `label` (and for my needs I have to do in this way), it doesn't work. 

Any suggestions?

![polyfill](https://user-images.githubusercontent.com/12846842/47211289-67364d80-d395-11e8-84d8-4138c0eaa757.gif)

JS Bin: https://output.jsbin.com/solopuq

_Originally posted by @acespace90 in https://github.com/mfranzke/datalist-polyfill/issues/43#issuecomment-431312871_

**Comment by mfranzke** [comment]
@acespace90, when nesting the _input_ into the _label_ element, please keep in mind to not insert the datalist element into the _label_ element as well, but as a the upfollowing sibling; compare to the W3C sample spec as well on this - I‘ve also modified their simple solution to include the _datalist_ within the _label_ as well, and it even also works the same by bluring the _select_ within the datalist on focus because of the surrounding _label_: https://jsbin.com/fegojipiqi/1/edit?html

**Comment by acespace90** [comment]
Unfortunately I cannot change the markup of the HTML also because nesting the `datalist` inside the `label` allows it to position properly because has `position: relative`. 
Anyway, I tried your jsbin on iOS and it still doesn't work.

**Comment by mfranzke** [comment]
@acespace90, the jsbin was meant to show that it even also doesn‘t work with some general (in this case W3C) markup.

I could even also set up a working jsbin later on.

**Comment by mfranzke** [comment]
@acespace90, what I meant by my previous post was that the `label` shouldn’t include the `datalist` element in general (and from my perspective even also it doesn’t need to include `input` elements, but that’s another discussion).

Even on the „simple“ solution (and not using my polyfill at all) provided within the [W3C specs](https://www.w3.org/TR/html52/sec-forms.html#the-datalist-element) to wrap the `option` elements within the `datalist` by a `select` you would face the same issue that you’ve reported on iOS - so this is what I wanted to reflect by providing their HTML code within that JSbin: https://jsbin.com/fegojipiqi/1/edit?html
The reason why is that „interactive content“ shouldn’t be placed into `label` elements, compare to https://developer.mozilla.org/en-US/docs/Web/HTML/Element/label#Interactive_content

**Comment by acespace90** [comment]
Understood. Thanks a lot.

**Comment by mfranzke** [comment]
Added those into the `readme` file.
