### ISSUE TITLE
TypeError: undefined is not an object (evaluating 'i.setAttributeNode')

### ISSUE THREAD

**Issue by damien-git** [mfranzke/datalist-polyfill#45]
I tried to use datalist-polyfill, but I am getting this error when clicking in a field with a datalist, and nothing is displayed when I type some characters:
  `TypeError: undefined is not an object (evaluating 'i.setAttributeNode')`
The markup is dynamically created with simple DOM methods. It works fine in non-Safari browsers. I tested with WebKit-based browser Epiphany.
  `<p><datalist id="nml_itemized_categories_datalist"><option value="..."></option>[many other options here]</datalist><input id="nml_itemized_categories_add_input" size="30" class="form-control" list="nml_itemized_categories_datalist"></p>`
It looks like the polyfill is supposed to create a select inside dataset (from what I can see in the demo, which works), but that select element is never created, and I don't see any error message about it.

**Comment by damien-git** [comment]
Actually, I found that I could avoid this bug by specifying the input type explicitly ("text" is the default type). A simple fix would be to accept a non-existent type attribute as "text".

**Comment by mfranzke** [comment]
Thanks a lot for reporting this - I‘ll look into it on the weekend and will provide a fix afterwards.

**Comment by mfranzke** [comment]
Please even also move the `datalist` element after the `input` element within your HTML structure, as it's much easier not to even also support this variation and that for even also matches the W3C specs (examples).

**Comment by damien-git** [comment]
You might want to document the expected position for the datalist. AFAIK the specs do not constrain its position in the document. I did notice a left margin issue when it is before the input.

**Comment by mfranzke** [comment]
@damien-git, totally agreed ! I'll mention it within the readme.
