### ISSUE TITLE
prevent option value to show in selectbox? Also, get option data

### ISSUE THREAD

**Issue by eddr** [mfranzke/datalist-polyfill#5]
Hi

Is there an option to hide the option value when the selectbox is open? I want to show the inner text, and get the value on select

**Comment by mfranzke** [comment]
Thanks a lot for your valuable feedback - I'll review it and come back with feedback.

**Comment by mitchhentges** [comment]
Hey, as a `datalist` noob, what's the "option value"? I've got a screenshot here of a `datalist` in Chrome - what should be hidden when the select is open?
![screenshot at 2018-03-16 17-15-49](https://user-images.githubusercontent.com/7784737/37549486-c465a774-293d-11e8-9895-8454c304fd01.png)

Sorry for not understanding :smile: :thinking:

**Comment by Kravimir** [comment]
ebbr seems to be talking about the <option> elements. In the DOM, they have a text property (representing the text inside them) and a value property (representing the value attribute). The value property of the selected option is used when the form is submitted. However, often developers don't intend for users to see that.

One solution would be to add a <input type="hidden"> element to give the value and probably change the name attributes of the original <input> and the new one as needed.

**Comment by mfranzke** [comment]
@Kravimir, I think that this is mainly covered by the different ways on how to define both value and text properties for datalists - please see section "Advanced" -> "Different ways of defining an option" on the demo page, which lists the different possibilities on how to define both text and value individually.

**Comment by mfranzke** [comment]
@eddr , I assume, that you're mentioning this because of the different behaviour of the already supporting browsers like e.g. Firefox just displaying the text in the suggestions, but inserting the values, whereas Chrome displays both properties (text and value). Correct?
![grafik](https://user-images.githubusercontent.com/787658/39638546-d784ae86-4fc6-11e8-88d5-937c4fd618a4.png)

**Comment by mfranzke** [comment]
As the browser vendors (GC vs. the others) don't seem to be aligned on this topic, I've decided to enable the `label`-attribute to serve as the definitive label being displayed, even if a value is being defined differing from the label. Check out the „Different ways of defining an option“ section on the demo page regarding this topic.
