### ISSUE TITLE
Minified JS includes unnecessary comments

### ISSUE THREAD

**Issue by nicholassaunders** [mfranzke/datalist-polyfill#58]
Thanks @mfranzke for an awesome library.

The only unfortunate thing I've encountered so far is that the minified JS file appears to include your code comments. According to my tests, this approximately doubles the size of the minified JS file.

I thought I would take a stab at resolving this myself through a PR, but, after reviewing the code, it is unclear to me how the ```datalist-polyfill.min.js``` file is being produced (build tool, minifier, config settings, etc.). If you wanted to shed some light on that, I would be glad to take on this effort. Otherwise, I would just be glad to see the update!

Thanks in advance.

**Comment by mfranzke** [comment]
@nicholassaunders, thanks a lot for raising this aspect, as well as remining me - I even also encountered this previously, but than somehow it sadly got forgotten.

I do the minifications still via CodeKit and will investigate on the reason why it seems to have changed in the meanwhile - most likely some update that I did w/o checking for the results accurately ...

**Comment by mfranzke** [comment]
Corrected the minification to even also remove all of the comments - the minified file is now much smaller again. I won't provide a release for this at the moment but will have it included with an upcoming one.
