### ISSUE TITLE
Option labels

### ISSUE THREAD

**Issue by Jaaap** [mfranzke/datalist-polyfill#60]
It would be nice if the polyfill supported option labels like these:
`<option value="1" label="1: Müller"/>`
These are only shown in the dropdown list, not in the input's value.

**Comment by mfranzke** [comment]
hej @Jaaap, thanks a lot for your request.

I'm not totally sure whether I'm probably not getting your point correctly - the demo page even already shows some different kind of markup "styles" regarding the defintion of `option` elements:
![image](https://user-images.githubusercontent.com/787658/58132984-fbfe7380-7c22-11e9-9fa8-aa1927080356.png)

To my understanding this even also already involves the last option out of this example, in which you define a label that is being shown within the "dropdown" whereas the value of the `value`-attribute is than being inserted as a value into the `input` field.
As you could see in the screenshot, this is even already the behaviour of the polyfill - tested in Safari 12.0.3 on Mac OS X.

I've additionally set up a JSFiddle with the HTML that you've provided:
https://jsfiddle.net/mfranzke/06cvk4g5/

**Comment by Jaaap** [comment]
Oh you're right. I'm sorry.
I was confused because Safari (suddenly?) has built-in support for datalist (but they do not show the label text).
