### ISSUE TITLE
When trying to use this in Safari 12.3, I get the following error

### ISSUE THREAD

**Issue by mfranzke** [mfranzke/datalist-polyfill#62]
When trying to use this in Safari 12.3, I get the following error: `[Error] TypeError: The HTMLInputElement.list getter can only be used on instances of HTMLInputElement`.

It's pointing to this line `constructor.prototype.list === undefined`.

```
  // Emulate the two properties regarding the datalist and input elements
  // list property / https://developer.mozilla.org/en/docs/Web/API/HTMLInputElement
  (function(constructor) {
    if (
      constructor &&
      constructor.prototype &&
      constructor.prototype.list === undefined
    ) {
```

The solution was to use `WKWebView` instead of `UIWebView` since it supports datalist. However, it's to note that this polyfill could be extended to work for all versions of Safari.

![Screen Shot 2019-06-03 at 5 41 15 PM](https://user-images.githubusercontent.com/8882123/58905048-de2b1700-86d6-11e9-96c2-aafcd6d5c087.png)

_Originally posted by @jscho13 in https://github.com/mfranzke/datalist-polyfill/issues/47#issuecomment-498793490_

**Comment by mfranzke** [comment]
@jscho13, thanks a lot for your feedback.

To my understanding, this is mainly about using a `datalist` element within a HTML website embedded in a webview within an app, in which the polyfill is included as well, isn't it?
And the solution that you're suggesting is about mentioning within the README that `WKWebView` should get used instead of `UIWebView`, right?

**Comment by jscho13** [comment]
Correct. It has no action on your part.

For users that have problems with `datalist` in an embedded webview within an app, they should be using `WKWebView` instead of `UIWebView`. I just wanted to inform them of the support newer HTML website shave.

**Comment by jscho13** [comment]
I can delete the comment in the original issue if you'd like.

**Comment by mfranzke** [comment]
sure, probably makes sense to clean up a little bit. Thank you !
