### ISSUE TITLE
Option list is drawn outside screen

### ISSUE THREAD

**Issue by hryamzik** [mfranzke/datalist-polyfill#7]
I'm using view-js and bootstrap (just css).
Installed with `npm install datalist-polyfill --save`. Imported in `main.js` as `import datalist from "datalist-polyfill"`.

![image](https://user-images.githubusercontent.com/1643962/32723681-b0144166-c86e-11e7-996c-3aeb897d5b0e.png)

This screenshot was made in Safari on OSX, the same behaviour is on mobile Safari.

P.S.: [jsfiddle](https://jsfiddle.net/hryamzik/y6qgc0g9/)

**Comment by hryamzik** [comment]
![image](https://user-images.githubusercontent.com/1643962/32723965-bd2929c4-c86f-11e7-8420-6c1af1725213.png)

Works a bit better if datalist is defined after input field. Can be reproduced without bootstrap as well.

**Comment by mfranzke** [comment]
@hryamzik, thanks a lot for your valuable feedback. Could you please provide a jsfiddle or something similar, as this would especially give me some insight into your test constellation (especially the HTML code chosen) ?

**Comment by hryamzik** [comment]
@mfranzke sure, there's actually a link in the original issue: [jsfiddle](https://jsfiddle.net/hryamzik/y6qgc0g9/).

**Comment by mfranzke** [comment]
I've provided a fix that would solve the problem of inputs styled as block-level-elements to even also have their polyfilling select element positioned correctly. Please consider moving the <datalist> element directly afterwards the <input> element within your source code, as this is the common structure and I wouldn't want to enhance the polyfill to even also mitigate/forsee any other code structure.
