### ISSUE TITLE
In the distribution package the file with the suffix min.js is not really a minified file

### ISSUE THREAD

**Issue by vinyfc93** [mfranzke/datalist-polyfill#74]
Hello, @mfranzke !

First of all, thanks for the great job!

I realized that the file called datalist-polyfill.min.js is actually just a file without the development comments, instead of being a real 'Minified', which usually also doesn't contain the indentation.

Is there a reason for that? or is it really a mistake?

**Comment by mfranzke** [comment]
@vinyfc93 , thanks a lot for that finding !

I've corrected to not have *.min.js files being forced to prettified.
