### ISSUE TITLE
Fails using onchange submit

### ISSUE THREAD

**Issue by chrisveness** [mfranzke/datalist-polyfill#9]
I am looking to use datalist-polyfill with an autosubmit function (the input element `onchange` event invokes `this.form.submit()`.

In Safari, when I click on the required entry in the select list, the partial entry in the input element gets submitted rather than the selected entry from the select list.

Example: www.movable-type.co.uk/dev/datalist-polyfill/auto-submit.html – type 'c' and select 'Cat' from the list; in Chrome, it submits value 'Cat', in Safari, the polyfill submits value 'c'.

Can you fix this, or do you have a workaround?

**Comment by mfranzke** [comment]
@chrisveness , as the users interaction lost focus on the input[list] itself, it's even also already submitting while the user might still navigate through the items in the list with the arrow keys (as the dropdown could get opened even also on clicking either up or down arrow keys initially).

This would be a common "problem" with other polyfills as well, as those even also would need to emulate the UI by some other HTML elements like e.g. select or some lists.

A simple solution might be to check for whether the focus still remains on the polyfilling select element afterwards.
